### ISSUE TITLE
Bring back message flag SESSION_OUTBOUND

### ISSUE THREAD

**Issue by majn** [vysheng/tgl#26]
I need this flag for determining if a message update is a message sent from the current device or a different one. Pidgin always prints user input right away, and I need a way to filter those messages so they don't show up twice.

See also this (working) patch I currently use on my test branch, I haven't figured out any other way to do this without changing libtgl: https://github.com/vysheng/tgl/commit/31cca917dccf5c1afeba7404e115f79decb0f526

**Comment by vysheng** [comment]
merged your pull request, thx
