### ISSUE TITLE
undefined refrence for static lib

### ISSUE THREAD

**Issue by mohamad-xtouch** [vysheng/tgl#41]
tnx for this library
when i build my project(c++) to create a executable file, rais this error

libs/libtgl.a(mtproto-client.o): In function `process_respq_answer':
mtproto-client.c:380: undefined reference to `tl_type_res_p_q'
mtproto-client.c:380: undefined reference to `skip_type_any'
....

please help me to solve this issue

**Comment by BenWiederhake** [comment]
I suggest closing this issue, as it doesn't apply anymore and the original reporter didn't bump for a while.
